type ProductExpansionSeed = {
  slug: string;
  name: string;
  brand: string;
  categorySlug: string;
  description: string;
  price: string;
  originalPrice: string;
  discountPercent: number;
  rating: string;
  reviewCount: number;
  stock: number;
  featured: boolean;
  isNew: boolean;
  colors: string[];
  sizes: string[];
  imageUrl: string;
  gallery: string[];
  tags: string[];
};

const photo = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;

const product = (
  values: Omit<ProductExpansionSeed, "price" | "originalPrice" | "discountPercent" | "gallery"> & {
    price: number;
    originalPrice?: number;
    gallery?: string[];
  },
): ProductExpansionSeed => ({
  ...values,
  price: String(values.price),
  originalPrice: String(values.originalPrice ?? values.price),
  discountPercent: values.originalPrice
    ? Math.round((1 - values.price / values.originalPrice) * 100)
    : 0,
  gallery: values.gallery ?? [values.imageUrl],
});

// The original editorial seed contains one or two products in each category.
// These additions bring every category to ten distinct, database-backed products.
export const expandedProductSeeds: ProductExpansionSeed[] = [
  // Electronics: 8 additions
  product({ slug: "mira-smartwatch", name: "Mira Active Smartwatch", brand: "Mira Labs", categorySlug: "electronics", description: "A slim fitness watch with week-long battery life, sleep tracking, and a calm monochrome display.", price: 6499, originalPrice: 7999, rating: "4.6", reviewCount: 84, stock: 18, featured: true, isNew: true, colors: ["Slate", "Sand"], sizes: [], imageUrl: photo("photo-1523275335684-37898b6baf30"), tags: ["wearable", "fitness", "new"] }),
  product({ slug: "keystone-mechanical-keyboard", name: "Keystone Mechanical Keyboard", brand: "Keystone", categorySlug: "electronics", description: "A compact mechanical keyboard with warm backlighting, tactile switches, and a satisfying aluminum deck.", price: 5890, originalPrice: 6490, rating: "4.7", reviewCount: 116, stock: 26, featured: false, isNew: false, colors: ["Charcoal", "Cream"], sizes: [], imageUrl: photo("photo-1587829741301-dc798b83add3"), tags: ["desk", "mechanical", "work"] }),
  product({ slug: "orbit-precision-mouse", name: "Orbit Precision Mouse", brand: "Orbit", categorySlug: "electronics", description: "A quiet wireless mouse shaped for long work sessions, with a glass-ready sensor and USB-C charging.", price: 2190, originalPrice: 2490, rating: "4.4", reviewCount: 67, stock: 42, featured: false, isNew: false, colors: ["Black", "Stone"], sizes: [], imageUrl: photo("photo-1527814050087-3793815479db"), tags: ["desk", "wireless", "work"] }),
  product({ slug: "volt-20k-power-bank", name: "Volt 20K Power Bank", brand: "Volt", categorySlug: "electronics", description: "A dependable 20,000 mAh power bank with dual USB-C output for commutes, flights, and long days away.", price: 2799, originalPrice: 3299, rating: "4.5", reviewCount: 205, stock: 33, featured: false, isNew: false, colors: ["Graphite"], sizes: [], imageUrl: photo("photo-1609592424859-0e7d0d2e4c8f"), tags: ["travel", "charging", "usb-c"] }),
  product({ slug: "slate-portable-ssd", name: "Slate Portable SSD 1TB", brand: "Slate", categorySlug: "electronics", description: "Fast, pocket-sized storage with a durable metal shell for creative files and everyday backups.", price: 7490, originalPrice: 8490, rating: "4.8", reviewCount: 93, stock: 12, featured: true, isNew: false, colors: ["Silver"], sizes: [], imageUrl: photo("photo-1597872200969-2b65d56bd16b"), tags: ["storage", "creative", "travel"] }),
  product({ slug: "arcade-gaming-headset", name: "Arcade Studio Gaming Headset", brand: "Arcade", categorySlug: "electronics", description: "Closed-back gaming headphones with a clear boom mic, soft memory foam, and balanced low-end.", price: 3990, originalPrice: 4490, rating: "4.3", reviewCount: 58, stock: 21, featured: false, isNew: true, colors: ["Black", "Cobalt"], sizes: [], imageUrl: photo("photo-1599669454699-248893623440"), tags: ["gaming", "audio", "new"] }),
  product({ slug: "north-usb-c-hub", name: "North 8-in-1 USB-C Hub", brand: "North", categorySlug: "electronics", description: "A compact aluminum hub that turns one USB-C port into a practical workstation connection.", price: 3290, originalPrice: 3690, rating: "4.5", reviewCount: 71, stock: 37, featured: false, isNew: false, colors: ["Space Grey"], sizes: [], imageUrl: photo("photo-1625842268584-8f3296236761"), tags: ["desk", "usb-c", "laptop"] }),
  product({ slug: "frame-1080-webcam", name: "Frame 1080 Webcam", brand: "Frame", categorySlug: "electronics", description: "A sharp, color-accurate webcam with a privacy shutter for calls, classes, and studio streaming.", price: 4590, originalPrice: 4990, rating: "4.2", reviewCount: 38, stock: 19, featured: false, isNew: true, colors: ["Black"], sizes: [], imageUrl: photo("photo-1587825140708-dfaf72ae4b04"), tags: ["video", "calls", "new"] }),

  // Fashion: 9 additions
  product({ slug: "field-cotton-tee", name: "Field Cotton T-Shirt", brand: "Field Notes", categorySlug: "fashion", description: "A substantial everyday tee cut from soft organic cotton with a clean neckline and easy drape.", price: 1290, originalPrice: 1590, rating: "4.5", reviewCount: 91, stock: 48, featured: false, isNew: false, colors: ["Ecru", "Ink", "Moss"], sizes: ["S", "M", "L", "XL"], imageUrl: photo("photo-1521572163474-6864f9cf17ab"), tags: ["cotton", "everyday", "basics"] }),
  product({ slug: "sora-poplin-shirt", name: "Sora Poplin Shirt", brand: "Sora", categorySlug: "fashion", description: "Crisp cotton poplin with a relaxed shoulder and a curved hem that works tucked or loose.", price: 2490, originalPrice: 2990, rating: "4.4", reviewCount: 63, stock: 35, featured: true, isNew: true, colors: ["White", "Sky"], sizes: ["S", "M", "L", "XL"], imageUrl: photo("photo-1603252110481-7ba873bf42ab"), tags: ["cotton", "shirt", "new"] }),
  product({ slug: "morrow-ribbed-top", name: "Morrow Ribbed Top", brand: "Morrow", categorySlug: "fashion", description: "A softly structured rib-knit top with a close fit and enough stretch for daily movement.", price: 1890, originalPrice: 2290, rating: "4.6", reviewCount: 45, stock: 29, featured: false, isNew: true, colors: ["Oat", "Black", "Rose"], sizes: ["XS", "S", "M", "L"], imageUrl: photo("photo-1485968579580-b6d095142e6e"), tags: ["knit", "layering", "new"] }),
  product({ slug: "cove-wrap-dress", name: "Cove Wrap Dress", brand: "Cove", categorySlug: "fashion", description: "A lightweight wrap dress with an adjustable waist and a print that moves easily from day to dinner.", price: 3690, originalPrice: 4290, rating: "4.7", reviewCount: 39, stock: 17, featured: true, isNew: false, colors: ["Terracotta", "Deep Green"], sizes: ["S", "M", "L"], imageUrl: photo("photo-1496747611176-843222e1e57c"), tags: ["dress", "occasion", "wrap"] }),
  product({ slug: "harbor-straight-jeans", name: "Harbor Straight Jeans", brand: "Harbor", categorySlug: "fashion", description: "Mid-rise straight denim with a little room through the leg and a softened wash from the first wear.", price: 3290, originalPrice: 3790, rating: "4.3", reviewCount: 74, stock: 31, featured: false, isNew: false, colors: ["Washed Blue", "Raw Indigo"], sizes: ["28", "30", "32", "34", "36"], imageUrl: photo("photo-1541099649105-f69ad21f3246"), tags: ["denim", "everyday", "straight"] }),
  product({ slug: "mistral-utility-jacket", name: "Mistral Utility Jacket", brand: "Mistral", categorySlug: "fashion", description: "A light utility jacket with generous pockets, matte hardware, and enough room for a knit underneath.", price: 4990, originalPrice: 5790, rating: "4.5", reviewCount: 28, stock: 14, featured: false, isNew: true, colors: ["Olive", "Stone"], sizes: ["S", "M", "L", "XL"], imageUrl: photo("photo-1551488831-00ddcb6c6bd3"), tags: ["outerwear", "utility", "new"] }),
  product({ slug: "monsoon-relaxed-hoodie", name: "Monsoon Relaxed Hoodie", brand: "Monsoon", categorySlug: "fashion", description: "A dense brushed-cotton hoodie with a relaxed shape for cool mornings and slow weekends.", price: 2890, originalPrice: 3390, rating: "4.6", reviewCount: 52, stock: 26, featured: false, isNew: false, colors: ["Clay", "Charcoal"], sizes: ["S", "M", "L", "XL"], imageUrl: photo("photo-1556821840-3a63f95609a7"), tags: ["fleece", "weekend", "layering"] }),
  product({ slug: "jaipur-block-print-kurta", name: "Jaipur Block-Print Kurta", brand: "Aangan", categorySlug: "fashion", description: "A breathable cotton kurta finished with hand-block printed details and an easy straight silhouette.", price: 2790, originalPrice: 3190, rating: "4.8", reviewCount: 67, stock: 22, featured: true, isNew: false, colors: ["Indigo", "Marigold"], sizes: ["S", "M", "L", "XL"], imageUrl: photo("photo-1583391733956-6c78276477e2"), tags: ["cotton", "indian", "block-print"] }),
  product({ slug: "tempo-training-legging", name: "Tempo Training Legging", brand: "Tempo", categorySlug: "fashion", description: "A supportive high-rise legging with a smooth matte finish and a phone-sized side pocket.", price: 2190, originalPrice: 2490, rating: "4.4", reviewCount: 43, stock: 33, featured: false, isNew: true, colors: ["Black", "Cobalt"], sizes: ["XS", "S", "M", "L"], imageUrl: photo("photo-1506629905607-d9d7c83c3ecf"), tags: ["activewear", "training", "new"] }),

  // Footwear: 9 additions
  product({ slug: "stride-runner-01", name: "Stride Runner 01", brand: "Stride", categorySlug: "footwear", description: "A responsive daily runner with breathable mesh, a stable heel, and a springy everyday ride.", price: 4290, originalPrice: 4990, rating: "4.6", reviewCount: 119, stock: 41, featured: true, isNew: true, colors: ["White", "Black"], sizes: ["6", "7", "8", "9", "10", "11"], imageUrl: photo("photo-1552674605-db6ffd4facb5"), tags: ["running", "daily", "new"] }),
  product({ slug: "lowline-canvas-sneaker", name: "Lowline Canvas Sneaker", brand: "Lowline", categorySlug: "footwear", description: "A simple canvas sneaker with a vulcanized sole and a shape that improves with wear.", price: 1990, originalPrice: 2290, rating: "4.3", reviewCount: 83, stock: 54, featured: false, isNew: false, colors: ["Natural", "Black", "Red"], sizes: ["6", "7", "8", "9", "10", "11"], imageUrl: photo("photo-1525966222134-fcfa99b8ae77"), tags: ["canvas", "casual", "everyday"] }),
  product({ slug: "coda-leather-derby", name: "Coda Leather Derby", brand: "Coda", categorySlug: "footwear", description: "A polished leather derby with a rounded toe and a cushioned footbed for long days on your feet.", price: 5490, originalPrice: 6290, rating: "4.7", reviewCount: 34, stock: 16, featured: true, isNew: false, colors: ["Cognac", "Black"], sizes: ["7", "8", "9", "10", "11"], imageUrl: photo("photo-1614252369475-531eba835eb1"), tags: ["leather", "formal", "work"] }),
  product({ slug: "sola-everyday-sandal", name: "Sola Everyday Sandal", brand: "Sola", categorySlug: "footwear", description: "A wide-strap sandal with a supportive footbed and a warm leather upper for easy summer days.", price: 2390, originalPrice: 2790, rating: "4.5", reviewCount: 47, stock: 28, featured: false, isNew: true, colors: ["Tan", "Black"], sizes: ["5", "6", "7", "8", "9"], imageUrl: photo("photo-1562273138-f46be4ebdf33"), tags: ["sandal", "summer", "new"] }),
  product({ slug: "aero-training-shoe", name: "Aero Training Shoe", brand: "Aero", categorySlug: "footwear", description: "A stable cross-training shoe with a grippy sole for gym floors, short runs, and active commutes.", price: 3790, originalPrice: 4290, rating: "4.4", reviewCount: 61, stock: 25, featured: false, isNew: false, colors: ["Grey", "Cobalt"], sizes: ["6", "7", "8", "9", "10", "11"], imageUrl: photo("photo-1538805060514-97d9cc17730c"), tags: ["training", "gym", "movement"] }),
  product({ slug: "mellow-walk-slip-on", name: "Mellow Walk Slip-On", brand: "Mellow", categorySlug: "footwear", description: "A lightweight slip-on with a flexible sole and soft lining for errands, travel, and everyday walking.", price: 2690, originalPrice: 2990, rating: "4.2", reviewCount: 36, stock: 44, featured: false, isNew: false, colors: ["Mushroom", "Navy"], sizes: ["6", "7", "8", "9", "10"], imageUrl: photo("photo-1495555961986-6d4c1ecb7be3"), tags: ["walking", "travel", "slip-on"] }),
  product({ slug: "riva-ballet-flat", name: "Riva Soft Ballet Flat", brand: "Riva", categorySlug: "footwear", description: "A softly gathered ballet flat with a flexible sole for polished comfort from office to evening.", price: 2890, originalPrice: 3390, rating: "4.6", reviewCount: 29, stock: 19, featured: false, isNew: true, colors: ["Berry", "Black"], sizes: ["5", "6", "7", "8", "9"], imageUrl: photo("photo-1560769629-975ec94e6a86"), tags: ["flat", "occasion", "new"] }),
  product({ slug: "trailhead-hiking-shoe", name: "Trailhead Hiking Shoe", brand: "Trailhead", categorySlug: "footwear", description: "A weather-ready hiking shoe with a protective toe, deep tread, and a comfortable all-day fit.", price: 4890, originalPrice: 5590, rating: "4.8", reviewCount: 48, stock: 13, featured: true, isNew: false, colors: ["Forest", "Slate"], sizes: ["7", "8", "9", "10", "11"], imageUrl: photo("photo-1551698618-1dfe5d97d256"), tags: ["hiking", "outdoors", "trail"] }),
  product({ slug: "court-form-sneaker", name: "Court Form Sneaker", brand: "Court Form", categorySlug: "footwear", description: "A clean low-top sneaker with a cushioned cupsole and subtle paneling inspired by classic court shoes.", price: 3490, originalPrice: 3990, rating: "4.5", reviewCount: 57, stock: 32, featured: false, isNew: false, colors: ["Chalk", "Green"], sizes: ["6", "7", "8", "9", "10", "11"], imageUrl: photo("photo-1549298916-b41d501d3772"), tags: ["sneaker", "court", "everyday"] }),

  // Beauty: 9 additions
  product({ slug: "clearwater-gel-cleanser", name: "Clearwater Gel Cleanser", brand: "Clearwater", categorySlug: "beauty", description: "A gentle low-foam cleanser with green tea and oat extract for a fresh, comfortable finish.", price: 790, originalPrice: 890, rating: "4.5", reviewCount: 174, stock: 63, featured: false, isNew: false, colors: ["Clear"], sizes: ["100 ml"], imageUrl: photo("photo-1556228720-195a672e8a03"), tags: ["skincare", "cleanser", "daily"] }),
  product({ slug: "serein-barrier-cream", name: "Serein Barrier Cream", brand: "Serein", categorySlug: "beauty", description: "A rich but breathable moisturizer with ceramides and squalane for a calm, cushioned skin feel.", price: 1290, originalPrice: 1490, rating: "4.7", reviewCount: 118, stock: 46, featured: true, isNew: true, colors: ["Ivory"], sizes: ["50 g"], imageUrl: photo("photo-1598440947619-2c35fc9aa908"), tags: ["skincare", "moisturizer", "new"] }),
  product({ slug: "sunroom-spf-50", name: "Sunroom SPF 50 Fluid", brand: "Sunroom", categorySlug: "beauty", description: "A lightweight broad-spectrum sunscreen that settles quickly without leaving a heavy cast.", price: 990, originalPrice: 1190, rating: "4.6", reviewCount: 206, stock: 58, featured: false, isNew: false, colors: ["Clear"], sizes: ["50 ml"], imageUrl: photo("photo-1556228578-8c89e6adf883"), tags: ["spf", "skincare", "daily"] }),
  product({ slug: "quiet-hour-vitamin-c", name: "Quiet Hour Vitamin C Serum", brand: "Quiet Hour", categorySlug: "beauty", description: "A brightening serum with a measured dose of vitamin C, licorice, and soothing panthenol.", price: 1690, originalPrice: 1990, rating: "4.4", reviewCount: 89, stock: 35, featured: false, isNew: true, colors: ["Amber"], sizes: ["30 ml"], imageUrl: photo("photo-1608248543803-ba4f8c70ae0b"), tags: ["serum", "brightening", "new"] }),
  product({ slug: "tint-room-lip-color", name: "Tint Room Lip Color", brand: "Tint Room", categorySlug: "beauty", description: "A comfortable satin lip color with buildable pigment and a soft blurred edge.", price: 690, originalPrice: 790, rating: "4.3", reviewCount: 71, stock: 42, featured: false, isNew: false, colors: ["Rosewood", "Brick", "Nude"], sizes: [], imageUrl: photo("photo-1586495777744-4413f21062fa"), tags: ["makeup", "lips", "color"] }),
  product({ slug: "nourish-oat-shampoo", name: "Nourish Oat Shampoo", brand: "Nourish", categorySlug: "beauty", description: "A gentle daily shampoo with oat protein and rice water for clean, soft, manageable hair.", price: 849, originalPrice: 999, rating: "4.5", reviewCount: 132, stock: 51, featured: false, isNew: false, colors: ["Pearl"], sizes: ["250 ml"], imageUrl: photo("photo-1556228852-80c6e6a8b40e"), tags: ["haircare", "shampoo", "daily"] }),
  product({ slug: "nourish-silk-conditioner", name: "Nourish Silk Conditioner", brand: "Nourish", categorySlug: "beauty", description: "A smooth conditioner with argan oil and amino acids for softer lengths without the weight.", price: 899, originalPrice: 1049, rating: "4.6", reviewCount: 97, stock: 39, featured: false, isNew: false, colors: ["Pearl"], sizes: ["250 ml"], imageUrl: photo("photo-1608571423902-eed4a5ad8108"), tags: ["haircare", "conditioner", "softness"] }),
  product({ slug: "daylight-body-lotion", name: "Daylight Body Lotion", brand: "Daylight", categorySlug: "beauty", description: "A fast-absorbing body lotion with shea butter and a clean, subtle botanical scent.", price: 749, originalPrice: 849, rating: "4.2", reviewCount: 63, stock: 47, featured: false, isNew: true, colors: ["White"], sizes: ["200 ml"], imageUrl: photo("photo-1584308666744-24d5c474f2ae"), tags: ["bodycare", "lotion", "new"] }),
  product({ slug: "after-rain-eau-de-parfum", name: "After Rain Eau de Parfum", brand: "After Rain", categorySlug: "beauty", description: "A fresh woody fragrance built around petrichor, bergamot, cedar, and a hint of white musk.", price: 2490, originalPrice: 2890, rating: "4.8", reviewCount: 44, stock: 18, featured: true, isNew: false, colors: ["Clear"], sizes: ["50 ml"], imageUrl: photo("photo-1547887538-e3a2f32cb1cc"), tags: ["fragrance", "woody", "gifting"] }),

  // Home: 9 additions
  product({ slug: "halo-pleated-table-lamp", name: "Halo Pleated Table Lamp", brand: "Halo Home", categorySlug: "home", description: "A warm table lamp with a pleated shade and a soft pool of light for bedside tables and reading corners.", price: 2890, originalPrice: 3390, rating: "4.6", reviewCount: 38, stock: 16, featured: true, isNew: true, colors: ["Linen", "Clay"], sizes: [], imageUrl: photo("photo-1507473885765-e6ed057f782c"), tags: ["lighting", "bedside", "new"] }),
  product({ slug: "loom-cotton-bedsheet", name: "Loom Cotton Bedsheet", brand: "Loom", categorySlug: "home", description: "A breathable 300-thread-count cotton bedsheet with a washed hand and quiet stripes.", price: 2490, originalPrice: 2990, rating: "4.7", reviewCount: 52, stock: 27, featured: false, isNew: false, colors: ["White", "Sage", "Blue"], sizes: ["Queen", "King"], imageUrl: photo("photo-1616486338812-3dadae4b4ace"), tags: ["bedroom", "cotton", "linen"] }),
  product({ slug: "stacked-cane-organizer", name: "Stacked Cane Organizer", brand: "Mori Objects", categorySlug: "home", description: "A handwoven cane organizer for shelves, entryways, and the small things that need a home.", price: 1190, originalPrice: 1390, rating: "4.4", reviewCount: 31, stock: 24, featured: false, isNew: false, colors: ["Natural"], sizes: [], imageUrl: photo("photo-1593085260707-5377ba37f868"), tags: ["storage", "cane", "organize"] }),
  product({ slug: "ember-cast-iron-pan", name: "Ember Cast Iron Pan", brand: "Ember", categorySlug: "home", description: "A pre-seasoned cast iron skillet made for crisp edges, slow braises, and years of cooking.", price: 2190, originalPrice: 2490, rating: "4.8", reviewCount: 85, stock: 19, featured: true, isNew: false, colors: ["Black"], sizes: ["10 inch"], imageUrl: photo("photo-1556911220-e15b29be8c8f"), tags: ["kitchen", "cookware", "cast-iron"] }),
  product({ slug: "stillwater-cushion", name: "Stillwater Linen Cushion", brand: "Stillwater", categorySlug: "home", description: "A square linen cushion with a feather-soft insert and a simple envelope closure.", price: 890, originalPrice: 1090, rating: "4.3", reviewCount: 24, stock: 36, featured: false, isNew: true, colors: ["Rust", "Oat", "Olive"], sizes: ["45 x 45 cm"], imageUrl: photo("photo-1584100936595-c0654b55a2e2"), tags: ["soft-goods", "living", "new"] }),
  product({ slug: "linework-wall-print", name: "Linework Wall Print", brand: "Linework", categorySlug: "home", description: "An archival art print of hand-drawn forms, sized to bring a quiet graphic note to a blank wall.", price: 1290, originalPrice: 1490, rating: "4.5", reviewCount: 19, stock: 25, featured: false, isNew: false, colors: ["Ink", "Sand"], sizes: ["A3"], imageUrl: photo("photo-1513519245088-0e12902e5a38"), tags: ["art", "wall", "graphic"] }),
  product({ slug: "nami-steel-bottle", name: "Nami Steel Bottle", brand: "Nami", categorySlug: "home", description: "A double-wall steel bottle that keeps water cool through workdays, commutes, and weekend walks.", price: 990, originalPrice: 1190, rating: "4.6", reviewCount: 112, stock: 48, featured: false, isNew: false, colors: ["Cobalt", "Cream"], sizes: ["750 ml"], imageUrl: photo("photo-1602143407151-7111542de6e8"), tags: ["kitchen", "travel", "steel"] }),
  product({ slug: "form-desk-tray", name: "Form Desk Tray", brand: "Form", categorySlug: "home", description: "A low-profile desk tray in powder-coated steel for keys, stationery, and daily essentials.", price: 690, originalPrice: 790, rating: "4.2", reviewCount: 27, stock: 33, featured: false, isNew: true, colors: ["Moss", "Ink"], sizes: [], imageUrl: photo("photo-1494438639946-1ebd1d20bf85"), tags: ["desk", "organize", "new"] }),
  product({ slug: "quiet-evening-candle", name: "Quiet Evening Candle", brand: "Quiet Evening", categorySlug: "home", description: "A hand-poured soy candle with cedar, black tea, and a trace of smoke in a reusable glass.", price: 790, originalPrice: 890, rating: "4.7", reviewCount: 58, stock: 42, featured: false, isNew: false, colors: ["Amber"], sizes: ["180 g"], imageUrl: photo("photo-1602874801006-e26e5b7a2c08"), tags: ["fragrance", "candle", "gifting"] }),

  // Accessories: 9 additions
  product({ slug: "roam-canvas-backpack", name: "Roam Canvas Backpack", brand: "Roam", categorySlug: "accessories", description: "A structured canvas backpack with a padded laptop sleeve and easy-access outer pocket.", price: 2390, originalPrice: 2790, rating: "4.5", reviewCount: 86, stock: 29, featured: true, isNew: false, colors: ["Olive", "Black"], sizes: [], imageUrl: photo("photo-1553062407-98eeb64c6a62"), tags: ["travel", "canvas", "laptop"] }),
  product({ slug: "sable-soft-tote", name: "Sable Soft Tote", brand: "Sable", categorySlug: "accessories", description: "A roomy soft tote with a wide shoulder strap and a magnetic closure for everyday carry.", price: 1890, originalPrice: 2190, rating: "4.4", reviewCount: 42, stock: 23, featured: false, isNew: true, colors: ["Tan", "Black"], sizes: [], imageUrl: photo("photo-1584917865442-de89df76afd3"), tags: ["bag", "everyday", "new"] }),
  product({ slug: "fold-card-wallet", name: "Fold Card Wallet", brand: "Fold", categorySlug: "accessories", description: "A slim leather card wallet with six slots and a center pocket for folded notes.", price: 990, originalPrice: 1190, rating: "4.6", reviewCount: 64, stock: 51, featured: false, isNew: false, colors: ["Cognac", "Black"], sizes: [], imageUrl: photo("photo-1627123424574-724758594e93"), tags: ["leather", "wallet", "gifting"] }),
  product({ slug: "sunline-angled-sunglasses", name: "Sunline Angled Sunglasses", brand: "Sunline", categorySlug: "accessories", description: "Angular acetate sunglasses with polarized lenses and a shape that suits everyday light.", price: 1690, originalPrice: 1990, rating: "4.3", reviewCount: 37, stock: 32, featured: false, isNew: true, colors: ["Tortoise", "Ink"], sizes: [], imageUrl: photo("photo-1511499767150-a48a237f0083"), tags: ["sunglasses", "summer", "new"] }),
  product({ slug: "meridian-field-watch", name: "Meridian Field Watch", brand: "Meridian", categorySlug: "accessories", description: "A clear, legible field watch with a brushed case and a replaceable nylon strap.", price: 3290, originalPrice: 3890, rating: "4.7", reviewCount: 49, stock: 14, featured: true, isNew: false, colors: ["Steel", "Olive"], sizes: [], imageUrl: photo("photo-1524592094714-0f0654e20314"), tags: ["watch", "field", "gifting"] }),
  product({ slug: "grain-leather-belt", name: "Grain Leather Belt", brand: "Grain", categorySlug: "accessories", description: "A full-grain leather belt with a softly brushed buckle and five considered fit points.", price: 1190, originalPrice: 1390, rating: "4.5", reviewCount: 26, stock: 39, featured: false, isNew: false, colors: ["Dark Brown", "Black"], sizes: ["30", "32", "34", "36", "38"], imageUrl: photo("photo-1624222247344-550fb60583dc"), tags: ["leather", "belt", "everyday"] }),
  product({ slug: "common-ground-cap", name: "Common Ground Cap", brand: "Common Ground", categorySlug: "accessories", description: "A six-panel cotton cap with an adjustable back and a small embroidered mark.", price: 690, originalPrice: 790, rating: "4.2", reviewCount: 33, stock: 44, featured: false, isNew: false, colors: ["Navy", "Stone", "Rust"], sizes: [], imageUrl: photo("photo-1473966968600-fa801b869a1a"), tags: ["cap", "cotton", "everyday"] }),
  product({ slug: "soft-shell-laptop-sleeve", name: "Soft Shell Laptop Sleeve", brand: "Soft Shell", categorySlug: "accessories", description: "A padded felt laptop sleeve with a protective zip and a pocket for a slim charger.", price: 1290, originalPrice: 1490, rating: "4.6", reviewCount: 54, stock: 28, featured: false, isNew: true, colors: ["Charcoal", "Sage"], sizes: ["13 inch", "14 inch", "15 inch"], imageUrl: photo("photo-1496181133206-80ce9b88a853"), tags: ["laptop", "desk", "new"] }),
  product({ slug: "waypoint-travel-pouch", name: "Waypoint Travel Pouch", brand: "Waypoint", categorySlug: "accessories", description: "A water-resistant travel pouch with elastic loops for cables, cards, and small daily tools.", price: 890, originalPrice: 990, rating: "4.4", reviewCount: 41, stock: 37, featured: false, isNew: false, colors: ["Cobalt", "Black"], sizes: [], imageUrl: photo("photo-1553531384-cc64ac80f931"), tags: ["travel", "organize", "cable"] }),

  // Sports: 9 additions
  product({ slug: "grounded-yoga-mat", name: "Grounded Yoga Mat", brand: "Grounded", categorySlug: "sports", description: "A dense, grippy yoga mat with enough cushioning for daily floor practice and stretching.", price: 1890, originalPrice: 2190, rating: "4.7", reviewCount: 128, stock: 34, featured: true, isNew: false, colors: ["Sage", "Cobalt"], sizes: ["6 mm"], imageUrl: photo("photo-1599447292180-45fd84092ef4"), tags: ["yoga", "practice", "wellness"] }),
  product({ slug: "orbit-match-football", name: "Orbit Match Football", brand: "Orbit Sport", categorySlug: "sports", description: "A durable machine-stitched football with a soft touch for training sessions and weekend matches.", price: 1090, originalPrice: 1290, rating: "4.5", reviewCount: 57, stock: 27, featured: false, isNew: true, colors: ["White", "Cobalt"], sizes: ["5"], imageUrl: photo("photo-1579952363873-27f3bade9f55"), tags: ["football", "training", "new"] }),
  product({ slug: "feather-badminton-racket", name: "Feather Carbon Racket", brand: "Feather", categorySlug: "sports", description: "A balanced carbon badminton racket with a forgiving sweet spot for club play and practice.", price: 2190, originalPrice: 2490, rating: "4.4", reviewCount: 36, stock: 18, featured: false, isNew: false, colors: ["Black", "Red"], sizes: [], imageUrl: photo("photo-1626224583764-f87db24ac4ea"), tags: ["badminton", "racket", "club"] }),
  product({ slug: "boundary-cricket-gloves", name: "Boundary Cricket Gloves", brand: "Boundary", categorySlug: "sports", description: "Lightweight batting gloves with flexible protection and a breathable palm for long innings.", price: 1490, originalPrice: 1690, rating: "4.6", reviewCount: 44, stock: 21, featured: false, isNew: false, colors: ["White", "Blue"], sizes: ["S", "M", "L"], imageUrl: photo("photo-1531415074968-036ba1b575da"), tags: ["cricket", "batting", "training"] }),
  product({ slug: "loop-resistance-band-set", name: "Loop Resistance Band Set", brand: "Loop", categorySlug: "sports", description: "Five color-coded resistance bands for warm-ups, strength work, and travel-friendly training.", price: 790, originalPrice: 990, rating: "4.8", reviewCount: 143, stock: 61, featured: false, isNew: true, colors: ["Mixed"], sizes: ["Set of 5"], imageUrl: photo("photo-1598971639058-fab3c3109a00"), tags: ["strength", "home-gym", "new"] }),
  product({ slug: "roam-gym-duffel", name: "Roam Gym Duffel", brand: "Roam", categorySlug: "sports", description: "A ventilated gym duffel with a separate shoe compartment and a wide, comfortable strap.", price: 1990, originalPrice: 2290, rating: "4.5", reviewCount: 62, stock: 26, featured: false, isNew: false, colors: ["Black", "Olive"], sizes: [], imageUrl: photo("photo-1556909212-d5b604d0c90d"), tags: ["gym", "bag", "training"] }),
  product({ slug: "arc-skipping-rope", name: "Arc Speed Skipping Rope", brand: "Arc", categorySlug: "sports", description: "A fast-turning skipping rope with adjustable length and smooth bearings for conditioning sessions.", price: 590, originalPrice: 690, rating: "4.3", reviewCount: 73, stock: 55, featured: false, isNew: false, colors: ["Black", "Orange"], sizes: [], imageUrl: photo("photo-1599058917212-d750089bc07e"), tags: ["cardio", "conditioning", "home-gym"] }),
  product({ slug: "stillwater-hydration-flask", name: "Stillwater Hydration Flask", brand: "Stillwater", categorySlug: "sports", description: "A leak-resistant stainless steel flask with a wide mouth and a looped carry cap.", price: 990, originalPrice: 1190, rating: "4.6", reviewCount: 88, stock: 46, featured: false, isNew: false, colors: ["Silver", "Black"], sizes: ["750 ml"], imageUrl: photo("photo-1551024709-8f23befc6f87"), tags: ["hydration", "outdoors", "steel"] }),
  product({ slug: "tempo-kettlebell-8kg", name: "Tempo Kettlebell 8kg", brand: "Tempo", categorySlug: "sports", description: "A cast iron kettlebell with a smooth powder coat and comfortable handle for foundational strength work.", price: 1590, originalPrice: 1890, rating: "4.7", reviewCount: 32, stock: 17, featured: true, isNew: false, colors: ["Charcoal"], sizes: ["8 kg"], imageUrl: photo("photo-1517963879433-6ad2b056d712"), tags: ["strength", "kettlebell", "training"] }),
];
